.github/workflows/docs.yml, doc/index.html
=> Add index to Rust docs

CONTRIBUTING.md, docs/content/objects/_index.md, docs/content/objects/schema.json
=> Document object info files

TUTORIAL.md, crates/camera/src/camera.rs
Allow using arrow keys to move the camera, as in Starcraft.
=> Allow using arrow keys to move the camera

crates/spawner/src/draft.rs
=> Change draft colour based on allowed state

Cargo.lock, assets/shaders/terrain.wgsl, crates/controller/src/selection/bookkeeping.rs, crates/core/src/projection.rs, crates/signs/src/markers.rs, crates/spawner/src/spawner.rs, crates/terrain/Cargo.toml, crates/terrain/src/lib.rs, crates/terrain/src/marker.rs, crates/terrain/src/shader.rs
Completes the second subtask of #36. Prior discussion can be found in #480 
Adds square markers to highlight selected buildings.
Draft until the following is done:
=> Square markers for buildings

crates/camera/src/camera.rs, crates/conf/src/conf.rs, docs/content/conf/_index.md
=> Add a configuration option for inverted mouse wheel zoom

crates/connector/src/game.rs, crates/net/src/lib.rs, crates/net/src/tasks/communicator.rs, crates/net/src/tasks/mod.rs
This makes it possible to use each channel independently in a possibly separate task.
=> de_net: Split API / channels

.github/workflows/release.yml
=> Publish nightly versions

.github/workflows/docs.yml
Fixes #517.
Relates to https://github.com/actions/deploy-pages/issues/188
=> Fix documentation publishing

crates/connector/tests/integration.rs
This commits tries to improve readability of the integration test.
=> de_connector: Improve i9n test

crates/net/src/connection/resend.rs, crates/net/src/tasks/resender.rs
This change makes the API (the channels) easier to use because it allows you to send the last reliable messages and close the channel without risking undelivered messages.
=> de_net: Wait a bit before stopping resneder

docs/src/conf.md
Reorder items in the example to match the order of the description above to improve readability.
=> Improve configuration docs

crates/net/src/tasks/dreceiver.rs
And make it more future proof.
=> de_net: Improve an import

Cargo.toml, crates/spawner/Cargo.toml, crates/spawner/src/spawner.rs
This change makes it possible to select enemy units. Further modifications are still needed, for example to allow attacking local player.
Relates to #249.
=> Introduce godmode feature flag

crates/connector/src/game/greceiver.rs, crates/connector/src/game/mod.rs, crates/connector/src/game/mreceiver.rs, crates/connector/src/game/preceiver.rs, crates/connector/src/game/state.rs, crates/connector/src/lib.rs, crates/connector/src/server.rs, crates/connector/tests/integration.rs, crates/net/src/connection/confirms.rs, crates/net/src/connection/databuf.rs, crates/net/src/connection/resend.rs, crates/net/src/header.rs, crates/net/src/lib.rs, crates/net/src/messages.rs, crates/net/src/protocol.rs, crates/net/src/socket.rs, crates/net/src/tasks/communicator.rs, crates/net/src/tasks/dreceiver.rs, crates/net/src/tasks/dsender.rs, crates/net/src/tasks/mod.rs, crates/net/src/tasks/sreceiver.rs, crates/net/src/tasks/ureceiver.rs, crates/net/src/tasks/usender.rs, docs/src/multiplayer/connector/README.md, docs/src/multiplayer/connector/encoding.md, docs/src/multiplayer/connector/protocol.md
=> de_net: Improve naming & docs

Cargo.lock, Cargo.toml, crates/multiplayer/Cargo.toml, crates/multiplayer/src/config.rs, crates/multiplayer/src/lib.rs, crates/multiplayer/src/netstate.rs, crates/multiplayer/src/network.rs, src/main.rs
=> Multiplayer: Impl connection to DE Connector

Cargo.lock, crates/multiplayer/Cargo.toml, crates/multiplayer/src/lib.rs, crates/multiplayer/src/messages.rs, crates/multiplayer/src/network.rs
=> de_multiplayer: Implement message (de)serialization

crates/controller/src/commands/handlers.rs, crates/controller/src/draft.rs, crates/controller/src/hud/minimap/fill.rs, crates/core/src/gconfig.rs, crates/loader/src/map.rs, crates/menu/src/singleplayer.rs, crates/spawner/src/gameend.rs, crates/spawner/src/spawner.rs
Playable is the player which is directly controlled by the user of the local computer. Local is a player which is controlled by the computer either directly by the user (i.e. playable) or by the AI (i.e. locally simulated).
Currently, all players are local because multiplayer is not yet implemented. This PR cleans up the naming and paves the way towards multiplayer.
=> Cleanup local vs playable confusion

README.md
=> README.md: Document godmode

crates/multiplayer/src/config.rs, crates/multiplayer/src/game.rs, crates/multiplayer/src/lib.rs, crates/multiplayer/src/lifecycle.rs, crates/multiplayer/src/messages.rs, crates/multiplayer/src/netstate.rs
=> Multiplayer: Impl game management functionality

crates/net/src/tasks/dreceiver.rs
=> de_net: Fix dreceiver termination

.github/workflows/rust.yml
So that a situation like #621 does not repeat.
=> CI: Ensure Cargo.lock is up-to-date

crates/behaviour/src/chase.rs, crates/construction/src/manufacturing.rs, crates/controller/src/commands/executor.rs, crates/pathing/src/fplugin.rs, crates/pathing/src/lib.rs, crates/pathing/src/pplugin.rs
So that it is consistent with our [coding style Guide](https://github.com/DigitalExtinction/Game/blob/main/CONTRIBUTING.md#coding-style).
=> Fix event struct type names

Cargo.toml, LICENSE, README.md
=> Change license from GPLv3 to AGPLv3

crates/lobby_client/src/endpoints.rs, crates/lobby_client/src/lib.rs, crates/menu/src/multiplayer/gamelisting.rs, crates/menu/src/multiplayer/joining.rs, crates/menu/src/multiplayer/mod.rs, crates/multiplayer/src/game.rs, crates/multiplayer/src/lib.rs
=> Impl game joining from menu

crates/audio/src/music.rs, crates/audio/src/spatial.rs, crates/conf/src/conf.rs, docs/src/conf.md
Config options:
- `master_volume` controls volume of all sounds multiplicatively
- `sound_volume` controls volume of sound effects
Closes #644.
=> Add master and SFX volume config

README.md
=> README.md: Fix CI badge

crates/lobby_client/src/endpoints.rs, crates/menu/src/multiplayer/joining.rs, crates/multiplayer/src/game.rs
Should have been done as part of #666.
=> Upgrade game joining

Cargo.lock, Cargo.toml, crates/connector/Cargo.toml, crates/connector/src/game/ereceiver.rs, crates/connector/src/game/greceiver.rs, crates/connector/src/game/mod.rs, crates/connector/src/game/preceiver.rs, crates/connector/src/game/state.rs, crates/connector/src/server.rs, crates/connector/tests/commands.rs, crates/messages/Cargo.toml, crates/messages/src/game.rs, crates/messages/src/lib.rs, crates/messages/src/server.rs, crates/multiplayer/Cargo.toml, crates/multiplayer/src/game.rs, crates/multiplayer/src/messages.rs, crates/multiplayer/src/stats.rs, crates/net/src/lib.rs
The messages themselves will be passed around places where access to the network is not needed.
=> Split de_net to de_net and de_messages

crates/net/src/connection/resend.rs
This add package deletion once it fails. It makes behavior of the method cleaner, however it wasn't "broken" before because the connection was dropped on failure.
=> de_net: Add tests & improve package resending

crates/net/src/connection/dispatch/mod.rs, crates/net/src/connection/dispatch/resends.rs, crates/net/src/connection/mod.rs, crates/net/src/tasks/mod.rs, crates/net/src/tasks/resender.rs, crates/net/src/tasks/sreceiver.rs, crates/net/src/tasks/usender.rs
This patch only moves code around and introduces several renames. It should have no impact on functionality whatsoever.
=> de_net: Reorganize package dispatch handling

crates/connector/src/game/ereceiver.rs, crates/connector/src/game/greceiver.rs, crates/connector/src/game/mreceiver.rs, crates/connector/src/game/preceiver.rs, crates/connector/src/server.rs, crates/connector/tests/commands.rs, crates/connector/tests/network.rs, crates/multiplayer/src/messages.rs, crates/net/src/connection/databuf.rs, crates/net/src/connection/delivery/deliveries.rs, crates/net/src/connection/delivery/mod.rs, crates/net/src/connection/delivery/pending.rs, crates/net/src/connection/delivery/received.rs, crates/net/src/connection/dispatch/mod.rs, crates/net/src/connection/dispatch/resends.rs, crates/net/src/connection/mod.rs, crates/net/src/header.rs, crates/net/src/lib.rs, crates/net/src/record.rs, crates/net/src/tasks/communicator.rs, crates/net/src/tasks/ureceiver.rs, crates/net/src/tasks/usender.rs
=> de_net: Add support for message ordering

crates/multiplayer/src/game.rs, crates/multiplayer/src/messages.rs, crates/multiplayer/src/stats.rs
=> Multiplayer: Use ordered messages where needed

Cargo.lock, crates/messages/src/players/mod.rs, crates/multiplayer/src/lib.rs, crates/multiplayer/src/playermsg.rs, crates/pathing/Cargo.toml, crates/pathing/src/lib.rs, crates/pathing/src/pplugin.rs, crates/pathing/src/syncing.rs, crates/types/src/path.rs
=> Multiplayer: impl path syncing

crates/net/src/connection/databuf.rs
=> de_net: Fix an assert

crates/combat/src/laser.rs, crates/combat/src/trail.rs
=> Play laser fire sound even for remote players

crates/controller/src/commands/executor.rs, crates/controller/src/frustum.rs, crates/controller/src/hud/minimap/draw.rs, crates/controller/src/mouse/pointer.rs, crates/core/src/events.rs, crates/uom/src/quantity.rs
`cargo +nightly udeps` complained with ``warning: the item `Projection` is imported redundantly`` (and similar).
=> Remove redundant imports

docs/src/multiplayer/connector/protocol.md
Changes from 68e742d3a49c1ffc2d2061222d33039c1308c859 were not reflected by the docs.
=> Fix networking documentation

docs/src/multiplayer/connector/README.md
=> Document game networking principles
