DigitalExtinction/Game

crates/controller/src/mouse.rs
Previously when dragging near the edge of the window, the game would sometimes crash with the below trace, seemingly due to a small rounding error of around a pixel.
```
thread 'Compute Task Pool (3)' panicked at 'Top right corner is not within screen range: Vec2(-0.22984987, 1.0011313)', crates/core/src/screengeom.rs:49:13
stack backtrace:
0: rust_begin_unwind
at /rustc/afaf3e07aaa7ca9873bdb439caec53faffa4230c/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at /rustc/afaf3e07aaa7ca9873bdb439caec53faffa4230c/library/core/src/panicking.rs:64:14
2: de_core::screengeom::ScreenRect::new
3: de_core::screengeom::ScreenRect::from_points
```
This change simply clamps the mouse position to within the screen bounds, to avoid this error.
=> Fix crash when dragging to the edge of the screen

crates/controller/src/hud.rs
The selection box should not be influenced by other UI nodes.
=> Make selection box position absolute

src/main.rs
Mouse grabbing does not work correctly on MacOS: the mouse is locked to the initial position instead of being confined to the primary window.
Relates to #354.
Relates to rust-windowing/winit#1093.
=> Do not grab cursor on MacOS

crates/controller/src/hud.rs, crates/controller/src/hud_components.rs, crates/controller/src/lib.rs, crates/controller/src/mouse.rs
Added initial HUD without actions #22
Added node for minimap #100
=> feat(controller): add simple blocking HUD

crates/core/src/visibility.rs, crates/signs/src/bars.rs, crates/signs/src/lib.rs
Implements #388
The bar is set visible using an event, and adds a timer component or updates an existing one. Once the timer expires, the visibility flag is unset and the timer removed.
Feel free to suggest changes, I wrote this very spontaneously.
=> Show updated health bars for a short time

crates/net/src/tasks/confirmer.rs, crates/net/src/tasks/resender.rs
The loop might take infinitely to finish in case that 0 messages needed to be resend or confirmed.
=> de_net: Ensure prompt task closure

CONTRIBUTING.md
One can easily visit the /crates directory and see all the crates themself. Each crate has Cargo.toml which should have an appropriate description. The list in CONTRIBUTING.md was thus redundant. Furthermore, it tends to get outdated.
=> CONTRIBUTING.md: Remove list of crates

crates/net/src/connection/confirms.rs, crates/net/src/tasks/cancellation.rs, crates/net/src/tasks/confirmer.rs, crates/net/src/tasks/mod.rs, crates/net/src/tasks/ureceiver.rs
Before the changes implemented in this commit, confirmer was never properly shut down. Even after all channels (`error`, `inputs` `outputs`) to the networking stack were dropped.
=> de_net: Fix network stack shutdown

crates/net/src/tasks/mod.rs, crates/net/src/tasks/resender.rs, crates/net/src/tasks/usender.rs
There was a bug with the original `break` -- it broke the for loop instead the outer loop. This is now fixed with loop labels.
Apart from fixing the behavior, after this modification, resender keeps running even if errors channel is closed as long as usender is still running. Until this change, users were force to a) keep the channel to avoid its closure and b) receive messages from it so it doesn't get full. There are situations when the user is no longer interested in connection errors but still needs the networking stack to keep running. Now, it is possible to just drop the errors channel to get that effect.
=> de_net: Fix & improve resender termination

crates/net/src/tasks/confirmer.rs, crates/net/src/tasks/dreceiver.rs, crates/net/src/tasks/resender.rs, crates/net/src/tasks/ureceiver.rs, crates/net/src/tasks/usender.rs
Log an error when any task (channel) terminates at a point when it is not expected. Termination should propagate from closures of the public channels (`MessageSender`, `MessageReceiver` and `ConnErrorReceiver`) to the more distant parts of the networking stack.
=> de_net: Improve task termination & logs

crates/net/src/net.rs
The maximum safe UDP payload is 508 bytes. This is a packet size of 576 (the "minimum maximum reassembly buffer size"), minus the maximum 60-byte IP header and the 8-byte UDP header.
Any UDP payload this size or smaller is guaranteed to be deliverable over IP (though not guaranteed to be delivered). Anything larger is allowed to be outright dropped by any router for any reason. Except on an IPv6-only route, where the maximum payload is 1,212 bytes. As others have mentioned, additional protocol headers could be added in some circumstances. A more conservative value of around 300-400 bytes may be preferred instead.
The maximum possible UDP payload is 67 KB, split into 45 IP packets, adding an additional 900 bytes of overhead (IPv4, MTU 1500, minimal 20-byte IP headers).
Any UDP packet may …
=> de_net: Change MAX_DATAGRAM_SIZE

crates/net/src/tasks/dreceiver.rs, crates/net/src/tasks/mod.rs, crates/net/src/tasks/resender.rs, crates/net/src/tasks/sreceiver.rs
It is desirable that system datagram receiver (`sreceiver`) keeps processing system datagrams (e.g. confirmations) until `resender` finishes. Otherwise, `resender` would keep resending and failing messages because there would be no means of datagram confirmation.
=> de_net: Change sreceiver cancellation mode

crates/controller/src/hud/minimap/nodes.rs
=> Draw minimap with correct aspect ratio

assets/shaders/rally_point.wgsl, crates/construction/src/manufacturing.rs, crates/controller/src/selection/bookkeeping.rs, crates/signs/src/lib.rs, crates/signs/src/line.rs
Closes #434.
First draft implemented in PR #484.
Follow ups:
- Update #2: mention that the lines must be updated to work properly on non-flat surface.
- Add functionality which hides the line when the camera is too far away to avoid clutter.
=> Display arrows from factory spawn to target

crates/connector/src/game.rs, crates/net/src/net.rs, crates/net/src/tasks/mod.rs
Port will be needed from multiple places and this commit makes the API more convenient to use as one has to handle the potential error only during the creation of the object.
=> de_net: make Network::port() non-fallible

.gitmodules
The submodule is no longer used. Should have been done as part of #542.
=> Remove obsoleted .gitmodules

crates/conf/src/conf.rs
Change config defaults to match docs. This was broken by mistake in #453.
This showcases why using #537 to generate the docs instead of doing it manually would be helpful and eliminate human error.
=> Fix config defualts

crates/connector/src/game/mod.rs, crates/connector/src/server.rs, crates/net/src/tasks/mod.rs
This makes the crate compatible with Bevy, needed because Bevy uses custom task executor.
=> de_net: Support custom task spawner

crates/camera/src/distance.rs, crates/conf/macros/src/lib.rs, crates/connector/tests/integration.rs, crates/construction/src/manufacturing.rs, crates/controller/src/commands/handlers.rs, crates/controller/src/hud/actionbar.rs, crates/controller/src/hud/minimap/fill.rs, crates/controller/src/hud/minimap/interaction.rs, crates/core/src/fs.rs, crates/gui/src/button.rs, crates/gui/src/textbox.rs, crates/lobby/src/auth/passwd.rs, crates/lobby_client/src/client.rs, crates/lobby_client/src/systems.rs, crates/map/src/hash.rs, crates/map/src/io.rs, crates/menu/src/create.rs, crates/menu/src/gamelisting.rs, crates/menu/src/mapselection.rs, crates/menu/src/singleplayer.rs, crates/movement/src/altitude.rs, crates/net/src/connection/databuf.rs, crates/net/src/tasks/dreceiver.rs, crates/net/src/tasks/dsender.rs
Rustfmt version 1.6.0 released on 2023-07-02 added support for let-else statement (PR https://github.com/rust-lang/rustfmt/pull/5690). Make the code compliant.
=> Re-format let-else statements

.github/workflows/docs.yml
Because of the draft condition, it is desirable to run the build on `ready_for_review` event.
=> CI: Fix & fine-tune docs build triggers

crates/connector/src/game/greceiver.rs, crates/connector/src/game/preceiver.rs, crates/connector/tests/integration.rs, crates/net/src/messages.rs
The main reason to ignore such messages is the case of a network issue (from server to client). The affected player is automatically kicked from the game in such a case. However, the client may not detect the network issue (e.g. because there was no traffic from the client to the server at the moment), therefore it may continue sending data to the game. Such a state might lead to issues within other game participants (e.g. receiving game sync messages from a unknown player).
Apart from the reason above, this is also a step towards better security. However it won't suffice on its own.
Fixes #583.
=> de_connector: Ignore message from non-participants

crates/connector/src/game/state.rs, crates/connector/tests/integration.rs, crates/net/src/messages.rs
This makes it compatible with `de_core::player::Player`. Numbering from 1 was chosen so that it is more user friendly.
=> de_connector: Start player numbering with 1

crates/multiplayer/src/lifecycle.rs
Shutting down if user cancels a game before it event starts (i.e. when still in multiplayer menu) must be handled separately.
=> Multiplayer: shutdown after game ends

crates/connector/src/clients.rs, crates/connector/src/game/greceiver.rs, crates/connector/src/game/mod.rs, crates/connector/src/lib.rs, crates/connector/src/server.rs
This fixes the issue of possible OpenGame package redelivery (which would lead to multiple games being opened).
Also, it is a step towards protection against a DoS attack as one could open infinite number of games and exhaust all ports as a result. To solve this completely, it would be necessary to limit source IP addresses not just sockets.
Relates to #547.
=> de_connector: Limit clients to max one game

crates/net/src/tasks/usender.rs, docs/src/multiplayer/connector/protocol.md
This will simplify reliable datagram deduplication because it could be assumed that there is only a small number of holes before the highest received ID.
=> de_net: Separate (non)reliable datagram counters

crates/connector/tests/integration.rs, crates/net/src/connection/book.rs, crates/net/src/connection/confirms.rs, crates/net/src/connection/resend.rs, crates/net/src/header.rs, crates/net/src/tasks/ureceiver.rs, docs/src/multiplayer/connector/protocol.md
It is proving hard to solve possible redundancies at all places where it matters. This solves this issue once for all for reliable packages.
=> de_net: Deduplicate reliable packages

crates/connector/src/game/greceiver.rs, crates/connector/src/server.rs, crates/multiplayer/src/game.rs, crates/net/src/lib.rs, crates/net/src/messages.rs
Since PR #605 no reliable packages are duplicated, therefore the only reason behind a player joining / opening multiple games at the same time is an error on client side. This exposes and handles the error.
=> Multiplayer: better join/open-game errors

.github/workflows/rust.yml, tools/todos.sh
Make sure that now TODO comments are left in production code so that situations like #580 do not happen again.
=> CI: Forbid TODO comments

crates/core/src/events.rs, crates/movement/src/cache.rs, crates/net/src/tasks/communicator.rs, crates/terrain/src/shader.rs, crates/tools/src/bounds.rs, src/main.rs
This fixes new lints added to Clippy released with Rust 1.71:
* default_constructed_unit_structs
* manual_while_let_some
=> Fix new Clippy lints

crates/conf/src/conf.rs, crates/conf/src/io.rs, crates/conf/tests/conf.yaml, crates/lobby_client/src/systems.rs, docs/src/conf.md
The address is needed to create a new game.
Note that during existing game joining, clients will fetch the **game** address from the lobby API.
=> Conf: Make DE Connector address configurable

crates/controller/src/hud/details.rs
The node was (20%, 30%) of the parent node (not the screen).
=> Fix HUD/details text node size

crates/lobby_client/src/plugin.rs
Most of systems sending / receiving the events are executed during `Update` so this change reduces potential for one frame delays.
=> lobby_client: Improve scheduling

crates/gui/src/lib.rs, crates/gui/src/toast.rs, crates/menu/src/gamelisting.rs, crates/menu/src/signin.rs
All toast events are sent from `Update` base set. This change removes the need to schedule the sending events `.before(ToastSet::ProcessEvents)` and reduces the opportunity for future one-frame-delay errors.
=> Improve toast event scheduling

CONTRIBUTING.md, README.md
It is the plan to make v1.0 (formerly v0.1) a full and enjoyable game. Better to market it as 1.0 instead of 0.1 and never reaching 1.0.
=> Update plan and rename v0.1 to v1.0

Cargo.lock, crates/camera/Cargo.toml, crates/camera/src/camera.rs, crates/loader/src/map.rs
This improves shadow quality because the cascade bounds are derived from camera distance from the terrain. Most objects are close to the terrain and the camera off nadir is limited, therefore majority of the shadows are in a limited distance range dependent on the camera to focus point distance.
Also, this change reduces number of cascades from 5 to 4, fixing this warning: `The number of cascades configured for a directional light exceeds the supported limit of 4.`
Fixes #574.
=> Improve shadows

assets/textures/skybox.png, crates/camera/src/lib.rs, crates/camera/src/skybox.rs
=> Add skybox

crates/menu/src/lib.rs, crates/menu/src/mainmenu.rs, crates/menu/src/menu.rs, crates/menu/src/multiplayer/create.rs, crates/menu/src/multiplayer/gamelisting.rs, crates/menu/src/multiplayer/mod.rs, crates/menu/src/multiplayer/requests.rs, crates/menu/src/multiplayer/signin.rs
This makes it more organized and makes it possible to generally handle multiplayer errors while in the menu.
=> Make menu states hiearchical

crates/menu/src/multiplayer/setup.rs, crates/multiplayer/src/config.rs, crates/multiplayer/src/game.rs, crates/multiplayer/src/lib.rs, crates/multiplayer/src/messages.rs
Previously, it was not possible to join an existing game without needlessly specifying maximum number of players (which had no effect).
=> Fix NetGameConf & StartMultiplayerEvent

crates/lobby/src/auth/db.rs, crates/lobby/src/db.rs, crates/lobby/src/games/db.rs, crates/lobby/src/games/endpoints.rs, crates/lobby/src/games/init.sql, crates/lobby_model/src/games.rs, crates/lobby_model/src/lib.rs, docs/src/multiplayer/openapi.yaml
- Thanks to uniqueness constraint on the ordinal, this serves as a maximum number of players constraint.
- It delegates ordinal (player number) assignment to the client who already receives such info from DE Connector.
Fixes #308.
=> Lobby: Make player ordinals client controlled

crates/connector/src/game/greceiver.rs, crates/connector/src/game/state.rs, crates/connector/tests/commands.rs, crates/multiplayer/src/game.rs, crates/net/src/lib.rs, crates/net/src/messages.rs
- This makes it possible to wait a bit until all clients enter the game and become prepared to receive messages related to game initialization (like some kind of to be implemented map object spawn messages).
- It changes how the game is started -- all clients must be ready for that.
- All of that in a unified step-by-step progression of readiness stages.
=> de_connector: Improve readiness staging

crates/menu/src/multiplayer/joining.rs, crates/menu/src/multiplayer/mod.rs, crates/menu/src/multiplayer/setup.rs, crates/menu/src/multiplayer/signin.rs
Previously, registration of different requests was scattered and might have led to duplicate plugin additions.
=> Refactor plugin registration in multiplayer menu

Cargo.lock, crates/construction/src/manufacturing.rs, crates/controller/src/commands/handlers.rs, crates/core/Cargo.toml, crates/core/src/gconfig.rs, crates/core/src/player.rs, crates/loader/src/map.rs, crates/menu/src/singleplayer.rs, crates/spawner/src/counter.rs, crates/spawner/src/despawner.rs, crates/spawner/src/gameend.rs, crates/spawner/src/spawner.rs
This removes the need to configure max players for the game. It will not be possible to set the value for multiplayer games with sparse player numbering (e.g. only player 1, 3, 4 joining).
=> Refactor GameConfig & related

.github/actions/rust/action.yml
Potentially fixes #685 (due to cached binary permissions).
=> Do not cache ~/.cargo/bin

crates/net/src/connection/resend.rs
`PriorityQueue` returns "greatest" items first, thus the timing ordering must be reversed so that the oldest (soonest to expire) packages are retrieved first.
=> de_net: Fix package resending

crates/net/src/connection/resend.rs
`MAX_TRIES` was used as if it was `MAX_RETRIES`.
=> de_net: Fix number of package resends

crates/connector/src/game/greceiver.rs, crates/connector/src/game/preceiver.rs, crates/connector/src/game/state.rs, crates/net/src/connection/dispatch/mod.rs, crates/net/src/lib.rs, crates/net/src/protocol.rs, crates/net/src/tasks/communicator.rs, crates/net/src/tasks/dsender.rs, crates/net/src/tasks/usender.rs, docs/src/multiplayer/connector/protocol.md
Continuous (per client) reliable message numbering is necessary for efficient out-of-order delivery detection, see ticket #700.
Packages to be delivered to multiple targets no longer share headers due the different package IDs. Therefore, the API for sending to multiple targets at once was removed.
=> de_net: Make package IDs separate for each connection

docs/src/multiplayer/connector/encoding.md
The message Rust objects were moved out to a different crate in 16469bf.
=> Docs: Fix a link

crates/connector/tests/common/mod.rs
Should have been done in 5d7e6a5. The error was not detected because the original binary (old name) was still present in the cache.
=> DE Lobby: Fix i9n tests

crates/controller/src/hud/minimap/interaction.rs
* Minimap no longer registers camera input when mouse is pressed down elsewhere and brought over the minimap
* Minimap camera responds to press instead of release
* Camera can now be dragged across the minimap in addition to clicking
I felt that at least with the current system, these new camera controls don't fit the existing event model, so I separated them to handle raw mouse input.
=> Improve minimap camera controls

crates/messages/src/players/entity.rs
No need to make the index transparent as long as once can easily use the entity directly in e.g. a hash map.
=> de_messages: Remove an unnecessary impl

crates/messages/src/players/geom.rs
Scaling is not used for top-level entity movement synchronization. This change will optimize network bandwidth usage.
=> de_messages: Always assume no scale in TransformNet

Cargo.lock, crates/construction/Cargo.toml, crates/construction/src/manufacturing.rs, crates/controller/Cargo.toml, crates/controller/src/draft.rs, crates/core/src/objects.rs, crates/loader/src/map.rs, crates/spawner/Cargo.toml, crates/spawner/src/despawner.rs, crates/spawner/src/lib.rs, crates/spawner/src/spawner.rs, crates/terrain/src/marker.rs
This centralization and reorganization of (de)spawning logic paves the way for the multiplayer. There will be a single place where synchronization mechanizes would be embedded. Apart from that, the code is now cleaner organized and more DRY.
=> Centralize (de)spawning logic

crates/construction/src/manufacturing.rs, crates/spawner/src/despawner.rs
This will be necessary during a multiplayer game to avoid desync (the authority is the local simulation).
=> Simulate destruction & manufacturing only for local

crates/spawner/src/despawner.rs
Despawning must work on all entities, including those without changed health.
=> de_spawner: Fix an ECS query

crates/messages/src/players/entity.rs, crates/multiplayer/src/lib.rs, crates/multiplayer/src/playermsg.rs, crates/spawner/src/despawner.rs, crates/spawner/src/spawner.rs
This PR makes it possible to send a network message regarding a non-locally simulated entity. This will be needed during e.g. health updates (triggered by a locally simulated attacking entity).
=> Multiplayer: Make non-local entity updates possible

crates/combat/src/health.rs, crates/combat/src/laser.rs, crates/combat/src/lib.rs, crates/objects/src/health.rs, crates/spawner/src/despawner.rs, crates/spawner/src/lib.rs
Centralization of the logic makes the code better organized and easier to extend or modified. It is a stepping stone for over network health synchronization.
=> Centralize entity health management

crates/net/src/header.rs
The client and the network intermediaries must not be trusted: a datagram with less than 4 bytes must be handled gracefully (without a crash).
Fixes #754.
=> de_net: Fix header parsing

crates/connector/src/lib.rs, crates/connector/src/main.rs
This is crutial for e.g. systemd units so that they can restart the service on-failure.
=> de_connector: Return non-zero exit code on failure

.github/workflows/test.yml
This fixes the following error from CI:
```
error: the option `Z` is only accepted on the nightly compiler
note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>
help: consider switching to a nightly toolchain: `rustup default nightly`
note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>
error: could not compile `sharded-slab` (lib)
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```
Relates to https://github.com/est31/cargo-udeps/issues/104 (one needs to pass +nightly to `cargo` so that correct / necessary rustc is used).
=> CI: Fix udeps

crates/multiplayer/src/playermsg.rs
This fixes: thread 'Compute Task Pool (4)' panicked at 'called `Option::unwrap()` on a `None` value', crates/multiplayer/src/playermsg.rs:270:78
Which was due to receiving a deregister message after the player left the game. This can happen as a race-condition just after game end or if the other player is kicked out due to network issues (but sends a message around the time of the kick).
Fixes #757.
=> Multiplayer: Fix entity de-registering

crates/combat/src/laser.rs, crates/combat/src/trail.rs, crates/messages/src/lib.rs, crates/messages/src/players/mod.rs, crates/messages/src/players/projectile.rs, crates/multiplayer/src/lib.rs, crates/multiplayer/src/messages.rs, crates/multiplayer/src/playermsg.rs
=> Mutiplayer: sync laser trails

crates/index/src/lib.rs, crates/index/src/precise/aabb.rs, crates/index/src/precise/collider.rs, crates/index/src/precise/grid.rs, crates/index/src/precise/index.rs, crates/index/src/precise/mod.rs, crates/index/src/precise/range.rs, crates/index/src/precise/segment.rs, crates/spawner/src/draft.rs
Currently, only collider based spatial indexing is implemented. It allows reasonably fast spatial queries, for example ray casting or AABB search applied on each entity collider.
It is the plan to extend `de_index` with point based indexing (as opposed to collider based indexing). Point based spatial queries have to potential to be much faster and yet sufficient for some important use-cases (i.e. energy grid graph construction). This PR reorganizes `de_index` so that we can add the alternative indexing alongside it.
Relates to #472.
=> de_index: Prep for faster indexing alternative

crates/messages/src/lib.rs
```
error: unused import: `Vec4Net`
--> crates/messages/src/players/mod.rs:5:48
|
5 | pub use geom::{TransformNet, Vec2Net, Vec3Net, Vec4Net};
|                                                ^^^^^^^
|
= note: `-D unused-imports` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_imports)]`
error: unused import: `PathError`
--> crates/messages/src/players/mod.rs:6:16
|
6 | pub use path::{PathError, PathNet};
|                ^^^^^^^^^
```
=> Fix clippy warnings

crates/conf/macros/tests/test_macro.rs
`stringify!()` macro has changed in between Rust versions.
=> de_conf: Fix a test

crates/controller/src/hud/minimap/fill.rs
Fixes #584.
All players are assigned a color based on their player number. It also changes the color of the units slightly to distinguish them from buildings.
In the future I think it would be nice that each player could choose their color from a list of curated colors that are visually distinctive, and then they would always be consistent across single player or multiplayer views. Or they are assigned a color, but then the UI would need to change in other ways so they would know which color they were assigned. This could be as simple as a color bar next to the their name in the game list, or some other color indicator in the HUD.
I'm just learning Rust and Bevy, so hopefully I did things properly. Let me know if you would like any changes.
=> Add basic enemy colors to minimap
